### ISSUE TITLE
Include a Changelog Link, within the F-Droid App', on Info' Page.  Not Present, as of: 1.0.5.

### ISSUE THREAD

**Issue by locutis-of-borg-1999** [caarmen/poet-assistant#2]

**Comment by caarmen** [comment]
Thanks for the suggestion.
I've added the Changelog here and created a merge request in fdroiddata: https://gitlab.com/fdroid/fdroiddata/merge_requests/1230/

Do I need to create a new tag here for the Changelog to be visible in F-Droid?

**Comment by locutis-of-borg-1999** [comment]
I'm pressed for time.  

Here is a link:   
https://f-droid.org/manual/html_node/Changelog.html#Changelog    

Thanks.

**Comment by caarmen** [comment]
I see the Change Log is appearing now on the F-Droid site.  I'll proceed to close this PR.  Don't hesitate to re-open it (or open a new one) if anything else is required.

Thanks!

**Comment by locutis-of-borg-1999** [comment]
I confif the changelog link appears in the F-Droid app' now, as well, noted upon update if v.1.0.7 (2016-FEB-22).  

Cool.  B-) 8-)

Thanks.

**Comment by locutis-of-borg-1999** [comment]
*I confirm...  ...update of...
