### ISSUE TITLE
Unable to use search on Android 15

### ISSUE THREAD

**Issue by gadgetguy08** [caarmen/poet-assistant#206]
Required before filing an issue:

I am a:

- [x] Real user of Poet Assistant
- [ ] Student or researcher
- [ ] Reporting an issue found by a software analysis or automation tool
- [ ] Other: Please explain

Latest version (1.30.8) displays the search icon on top of the screen in the notification area (with battery level, network strength, etc.) and is unusable on Android 15 Graphene OS.  Note this occurs in portrait mode only.  Landscape mode works.

**Comment by caarmen** [comment]
Thanks for bringing this to my attention.

I indeed do see a difference between 1.30.7 and 1.30.8.

|1.30.7|1.30.8|
|---|---|
|<img width="540" alt="image" src="https://github.com/user-attachments/assets/4ee38d31-d4fc-4bfe-aada-74a700d81efd">|<img width="540" alt="image" src="https://github.com/user-attachments/assets/2f489e65-bb44-45fe-af2d-ddef5436708f">|

These screenshots are from a Google emulator, using Android 15, Default Android System Image. it's the closest I could get to Graphene OS 😅 

On the emulator, the search icon is still clickable. But I can indeed see that it's higher up than the previous release.

I'll put updates here as I find more info about this change, or when there's a fix!

**Comment by caarmen** [comment]
This regression was introduced in b7522fa00c24a6674f082accd35d7f84c000215c

**Comment by caarmen** [comment]
Thanks again for reporting this, and being on the bleeding edge with the latest Android version 😁 

Release 1.30.9 fixes a few related things:
* The search icon being mixed with the status bar items.
* The last items of a long list being unclickable under the navigation bar.
* The content at the top of the settings and about screens being unclickable under the status bar.

However, after pushing this release, I realized that there's still at least one remaining issue: in landscape mode, if you have a navigation bar (you're not using gesture navigation), the overflow menu (the three dots) is unclickable, under the navigation bar:

![image](https://github.com/user-attachments/assets/67d269ce-a1c3-4a02-ae12-e988c0929081)

**Comment by gadgetguy08** [comment]
working for me now.  thanks!
sorry for the slow response.
