### ISSUE TITLE
Wish: looking up words from within reader

### ISSUE THREAD

**Issue by LuccoJ** [caarmen/poet-assistant#4]
Another feature request, which may or may not be simple to implement depending on how Android treats text box selections, I guess.

It would be handy if either (in order of preference) when you
* have the cursor on a word (making it underlined)
* have a word selected (giving the ability to copy and paste)
* copy a word into the clipboard

from inside the Reader, then subsequently hitting the Search button or going to Rhymer/Thes/Dict would result in that word being directly looked up.

This way, if you're using the Reader as a writing pad for your poem, you could look up words without having to re-type them.

**Comment by caarmen** [comment]
Long pressing on a word in the reader brings up a popup which allows you to lookup the word in the rhymer, thesaurus, or dictionary.
